### ISSUE TITLE
How about support of Sublime 3?

### ISSUE THREAD

**Issue by algarecu** [jvantuyl/sublime_diagram_plugin#30]
Exception: PlantUML does not appear functional
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "/Users/Library/Application Support/Sublime Text 3/Packages/jvantuyl-sublime_diagram_plugin-9c079d7/diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "/Users/Library/Application Support/Sublime Text 3/Packages/jvantuyl-sublime_diagram_plugin-9c079d7/diagram/**init**.py", line 49, in setup
    raise Exception('No working processors found!')
Exception: No working processors found!

**Comment by tooh** [comment]
same here. Any progress on this ?

**Comment by jvantuyl** [comment]
Hmmmmm, Sublime Text 3 *should* be supported.  It appears unable to find a viewer.  What version of MacOS X are you running?

**Comment by algarecu** [comment]
Mavericks at the time.

**Comment by bAmrish** [comment]
I am getting the similar error for Sublime Text 3 on Ubuntu OS 14.04. I have attached stacktrace if that helps:

```
reloading plugin sublime_diagram_plugin.diagram_plugin
plugins loaded
EasyDiff: svn not found or is not working!
EasyDiff: git 1.9.1
EasyDiff: hg not found or is not working!
Viewer Setting: Preview
Loading processor class: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Unable to load processor: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Traceback (most recent call last):
  File "/home/abharatiya/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/__init__.py", line 42, in setup
    proc.load()
  File "/home/abharatiya/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/plantuml.py", line 56, in load
    self.check_dependencies()
  File "/home/abharatiya/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/plantuml.py", line 66, in check_dependencies
    **EXTRA_CALL_ARGS
  File "./subprocess.py", line 523, in call
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'java'
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "/home/abharatiya/softwares/sublime_text_3/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/home/abharatiya/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "/home/abharatiya/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/__init__.py", line 49, in setup
    raise Exception('No working processors found!')
Exception: No working processors found!
```

**Comment by jvantuyl** [comment]
Hmmmm.  Do you have Java installed?  PlantUML requires Java.

**Comment by bAmrish** [comment]
Yes. I have jdk 1.7 (oracle) installed.

**Comment by lintanghui** [comment]
you may need to add the graphviz  to the PATH,and add a env variable GRAPHVIZ_DOT point to dot. It may help.

**Comment by taggartaa** [comment]
Had this same issue, it was resolved when I installed graphviz.

**Comment by arenaq** [comment]
I am unable to make it work on Windows 10. It seems it is not installed. I used Package Control:Add Repository and pasted link to gitlab. It says it was successfully installed, but I cant see it in list when I want to remove it. I have Graphviz installed and it is working fine in Android Studio with PlantUML plugin.

**Comment by japixxx** [comment]
Windows 10 problem was that it cannot find java exceutable from path. Path is not searched 
has_java = call(
           ["java", "-version"],
            **EXTRA_CALL_ARGS
        )
hack to fix 
add  variable pointing to java.exe to beginin planuml.py

JAVA_PATH = 'C:\\Program Files\\Java\\jdk1.8.0_131\\jre\\bin\\java'

replace all 'java' and "java"  with JAVA_PATH in planuml.py.

... everything works at least for me

**Comment by jvantuyl** [comment]
Sublime Text 3 works now.
