### ISSUE TITLE
installing on Mac results in console error

### ISSUE THREAD

**Issue by elisawyer** [jvantuyl/sublime_diagram_plugin#34]
Upon adding the sublime_diagram_plugin folder to Packages, Sublime Text 3 sent the following to its console (seems it's *almost* working):

reloading plugin sublime_diagram_plugin.diagram_plugin
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m.plugin_loaded()
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/sublime_diagram_plugin/diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "/Users/<username>//Library/Application Support/Sublime Text 3/Packages/sublime_diagram_plugin/diagram/__init__.py", line 34, in setup
    print("Viewer Setting: " + sublime_settings.get("viewer"))
TypeError: Can't convert 'NoneType' object to str implicitly
generating syntax summary
no command for selector: noop:
using gpu buffer for window
SublimeLinter: annotations activated: <builtin>

**Comment by jvantuyl** [comment]
Okay, there was an issue when the viewer wasn't explicitly set in the config file.  There's a version on the develop branch that addresses this.  Could you see if it works for you?
