### ISSUE TITLE
Package control says it's MISSING

### ISSUE THREAD

**Issue by kimaero** [jvantuyl/sublime_diagram_plugin#50]
Impossible to install via package control as it shows 'MISSING' status: http://shot.kim.aero/20170209150449-0cd4bbfb-71f9-4dea-a8a2-e711c1704e8b-wqLR6.png

Tried to install from repository, got the following: 
```
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "/Users/denis/Library/Application Support/Sublime Text 3/Packages/sublime_diagram_plugin/diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "/Users/denis/Library/Application Support/Sublime Text 3/Packages/sublime_diagram_plugin/diagram/__init__.py", line 36, in setup
    print("Viewer Setting: " + sublime_settings.get("viewer"))
TypeError: Can't convert 'NoneType' object to str implicitly
generating syntax summary
```

**Comment by kevinmullin** [comment]
I am seeing this same error on latest version of sublime text 3

**Comment by bAmrish** [comment]
I am getting the same error.  I have a Mac running Sublime text 3. Any solutions?

**Comment by bAmrish** [comment]
Just realised that the issue disappears after you restart sublime after installation. Probably some sort of notification after installation would be useful.

**Comment by jvantuyl** [comment]
I have a pull request for this now.  Let's see if it gets in.  wbond/package_control_channel#6970

**Comment by jvantuyl** [comment]
Duplicates #44 , closing as a duplicate.
