### ISSUE TITLE
Sublime 3 on mac: Unable to load diagram plugin, check console for details.

### ISSUE THREAD

**Issue by paragbaxi** [jvantuyl/sublime_diagram_plugin#65]
Upon install package via package control right after installing Graphviz and java via homebrew

**Comment by paragbaxi** [comment]
`b'PlantUML version 1.2018.01 (Sun Jan 28 13:08:22 EST 2018)\n(GPL source distribution)\nJava Runtime: Java(TM) SE Runtime Environment\nJVM: Java HotSpot(TM) 64-Bit Server VM\nJava Version: 10.0.2+13\nOperating System: Mac OS X\nOS Version: 10.13.6\nDefault Encoding: UTF-8\nLanguage: en\nCountry: US\nMachine: nopsecs-macbook.nopsec.com\nPLANTUML_LIMIT_SIZE: 4096\nProcessors: 8\nMax Memory: 4,294,967,296\nTotal Memory: 268,435,456\nFree Memory: 260,575,560\nUsed Memory: 7,859,896\nThread Active Count: 1\n\nThe environment variable GRAPHVIZ_DOT has not been set\nDot executable is /usr/local/bin/dot\nDot version: dyld: Library not loaded: /usr/local/lib/libgvc.6.dylib   Referenced from: /usr/local/bin/dot   Reason: image not found\nWarning : cannot determine dot version\n'
PlantUML Smoke Check:
b'The environment variable GRAPHVIZ_DOT has not been set\nDot executable is /usr/local/bin/dot\nDot version: dyld: Library not loaded: /usr/local/lib/libgvc.6.dylib   Referenced from: /usr/local/bin/dot   Reason: image not found\nWarning : cannot determine dot version\n'
Unable to load processor: <class 'Diagram.diagram.plantuml.PlantUMLProcessor'>
Traceback (most recent call last):
  File "/Users/pbaxi/Library/Application Support/Sublime Text 3/Packages/Diagram/diagram/__init__.py", line 45, in setup
    proc.load()
  File "/Users/pbaxi/Library/Application Support/Sublime Text 3/Packages/Diagram/diagram/plantuml.py", line 121, in load
    self.check_plantuml_functionality()
  File "/Users/pbaxi/Library/Application Support/Sublime Text 3/Packages/Diagram/diagram/plantuml.py", line 153, in check_plantuml_functionality
    raise Exception('PlantUML does not appear functional')
Exception: PlantUML does not appear functional
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "/Users/pbaxi/Library/Application Support/Sublime Text 3/Packages/Diagram/diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "/Users/pbaxi/Library/Application Support/Sublime Text 3/Packages/Diagram/diagram/__init__.py", line 52, in setup
    raise Exception('No working processors found!')
Exception: No working processors found!`

**Comment by jvantuyl** [comment]
The plugin found a graphviz dot executable in /usr/local/bin. Is that an old one? It seems to give an error related to broken libraries when plantuml tries to use it. I don’t think this is anything I can fix.
